name: .NET Core NUnit Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print GITHUB_TOKEN value
      run: |
        echo "GITHUB_TOKEN Value: $GITHUB_TOKEN"
      # 这里使用 $GITHUB_TOKEN 来引用环境变量
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Create Test Results Directory
      run: mkdir -p ./test/TestResults

    - name: Run NUnit tests
      run: dotnet test ./test/Test.csproj --no-build --logger "trx;LogFileName=testresults.trx" --results-directory ./test/TestResults

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: './test/TestResults/*.trx'
        GITHUB_TOKEN: ${{ github.token }}